M48
; DRILL file KiCad 10.0.5 date 2026-09-21T18:16:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-21T18:16:17+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X53.665Y-21.11
X53.665Y-26.89
T2
X57.6Y-9.5
X57.6Y-12.5
T3
X4.0Y-4.0
X4.0Y-71.0
X56.0Y-4.0
X56.0Y-71.0
M30
