"""Generate camera_module.wrl: OV2640 module with its 24P ribbon FOLDED BACK over
the FPC connector so the module lies on the board (ESP32-CAM style) instead of
hanging past the board edge. Uses only Box and IndexedFaceSet (KiCad's VRML
loader ignores Cylinder primitives). Units 0.1 inch. Frame: origin at J2
centre, +Y = toward the board edge, -Y = toward board centre, +Z up.

Geometry (mm):
  segment A  : ribbon leaves the connector toward the edge, z 1.0, y -1 .. +2.5
  fold       : U-turn at y +2.5 .. +3.5, z 1.0 .. 2.4
  segment B  : ribbon runs back over the connector toward board centre at z 2.4,
               y +2.5 .. -14
  module     : 9 x 9 mm sensor PCB whose edge joins the ribbon at y -14,
               centre y -18.5, sitting on a 2.4 mm foam pad; lens faces up
"""
import math
from pathlib import Path

OUT = Path(__file__).with_name("models") / "camera_module.wrl"
U = 1 / 2.54  # mm -> 0.1 inch


def mat(d, s=(0.2, 0.2, 0.2), sh=0.3):
    return (f"appearance Appearance {{ material Material {{ diffuseColor {d[0]} {d[1]} {d[2]} "
            f"specularColor {s[0]} {s[1]} {s[2]} shininess {sh} }} }}")


def box(cx, cy, cz, sx, sy, sz, m):
    return (f"Transform {{ translation {cx*U:.4f} {cy*U:.4f} {cz*U:.4f} children Shape {{ {m} "
            f"geometry Box {{ size {sx*U:.4f} {sy*U:.4f} {sz*U:.4f} }} }} }}\n")


def cylinder(cx, cy, z0, z1, r, m, n=40):
    pts = []
    for z in (z0, z1):
        for i in range(n):
            a = 2 * math.pi * i / n
            pts.append((cx + r * math.cos(a), cy + r * math.sin(a), z))
    pts.append((cx, cy, z0))
    pts.append((cx, cy, z1))
    faces = []
    for i in range(n):
        j = (i + 1) % n
        faces.append([i, j, n + j, n + i])
        faces.append([2 * n, j, i])
        faces.append([2 * n + 1, n + i, n + j])
    coord = " ".join(f"{x*U:.4f} {y*U:.4f} {z*U:.4f}" for x, y, z in pts)
    idx = " ".join(" ".join(map(str, f)) + " -1" for f in faces)
    return (f"Shape {{ {m} geometry IndexedFaceSet {{ solid FALSE creaseAngle 0.8 "
            f"coord Coordinate {{ point [ {coord} ] }} coordIndex [ {idx} ] }} }}\n")


def half_pipe(cy, z_mid, r, width, m, n=16):
    """Half-cylinder shell (the ribbon U-turn) around an axis parallel to X at
    (y=cy, z=z_mid), sweeping from the bottom (-Z) around +Y to the top (+Z)."""
    pts = []
    for x in (-width / 2, width / 2):
        for i in range(n + 1):
            a = -math.pi / 2 + math.pi * i / n  # -90deg (bottom) -> +90deg (top), bulging toward +Y
            pts.append((x, cy + r * math.cos(a), z_mid + r * math.sin(a)))
    faces = []
    for i in range(n):
        faces.append([i, i + 1, n + 1 + i + 1, n + 1 + i])
    coord = " ".join(f"{x*U:.4f} {y*U:.4f} {z*U:.4f}" for x, y, z in pts)
    idx = " ".join(" ".join(map(str, f)) + " -1" for f in faces)
    return (f"Shape {{ {m} geometry IndexedFaceSet {{ solid FALSE creaseAngle 1.0 "
            f"coord Coordinate {{ point [ {coord} ] }} coordIndex [ {idx} ] }} }}\n")


ribbon = mat((0.85, 0.52, 0.16), (0.35, 0.3, 0.25), 0.5)
copper = mat((0.85, 0.70, 0.35), (0.8, 0.7, 0.4), 0.8)
white = mat((0.93, 0.93, 0.90))
fr4 = mat((0.05, 0.09, 0.07))
holder = mat((0.13, 0.13, 0.14), (0.15, 0.15, 0.15), 0.3)
gloss = mat((0.05, 0.05, 0.06), (0.6, 0.6, 0.6), 0.85)
silver = mat((0.72, 0.72, 0.74), (0.9, 0.9, 0.9), 0.9)
glass = mat((0.12, 0.16, 0.42), (1.0, 1.0, 1.0), 1.0)
foam = mat((0.25, 0.25, 0.27))
label = mat((0.9, 0.9, 0.9))

RW = 14.0          # ribbon width
ZA = 1.0           # ribbon height inside connector
ZB = 2.4           # ribbon height on the way back over the connector
Y_FOLD = 2.5       # where the U-turn starts (toward the edge)
Y_END = -14.0      # where the ribbon meets the module
CY = Y_END - 4.5   # module centre
Z_MOD = ZB         # module PCB bottom rests at ribbon height (foam pad underneath)

s = "#VRML V2.0 utf8\n# OV2640 module, ribbon folded back onto the board. Generated by gen_camera_wrl.py\n"
# segment A (y -1 .. +2.5) with stiffener and copper fingers
s += box(0, (-1 + Y_FOLD) / 2, ZA, RW, Y_FOLD + 1, 0.2, ribbon)
s += box(0, 1.2, ZA + 0.11, 12, 1.2, 0.03, copper)
s += box(0, -0.5, ZA + 0.1, RW, 3.0, 0.3, white)
# U-turn: half pipe radius 0.7 centred at y=Y_FOLD, z=(ZA+ZB)/2
r = (ZB - ZA) / 2
s += half_pipe(Y_FOLD, (ZA + ZB) / 2, r, RW, ribbon)
# segment B (y +2.5 .. -14) at ZB
s += box(0, (Y_FOLD + Y_END) / 2, ZB, RW, Y_FOLD - Y_END, 0.2, ribbon)
# foam pad under the module, z 0 .. ZB-0.1
s += box(0, CY, (ZB - 0.1) / 2, 8, 8, ZB - 0.1, foam)
# sensor PCB 9x9x1 at Z_MOD .. +1
s += box(0, CY, Z_MOD + 0.5, 9, 9, 1.0, fr4)
# lens holder 8.5x8.5x3.5
s += box(0, CY, Z_MOD + 1.0 + 1.75, 8.5, 8.5, 3.5, holder)
zt = Z_MOD + 4.5  # top of holder
s += cylinder(0, CY, zt, zt + 1.8, 3.25, gloss)          # barrel
s += cylinder(0, CY, zt + 1.8, zt + 2.1, 3.45, silver)   # ring
s += cylinder(0, CY, zt + 2.09, zt + 2.15, 2.5, gloss)   # bore
s += cylinder(0, CY, zt + 2.15, zt + 2.3, 1.7, glass)    # glass
s += box(3.2, CY + 3.6, Z_MOD + 1.05, 1.6, 0.4, 0.05, label)

OUT.write_text(s, encoding="utf-8")
print("wrote", OUT, len(s), "bytes; module centre at local y", CY, "mm (board y", 6.5 - CY, ")")
