"""Generate display_module.wrl: the common 1.3" 240x240 IPS ST7789 module with a
7-pin 2.54 mm header (GMT130-V1.0 / ZJY133T-IG01 board; lcdwiki "1.3inch IPS
Module"). Geometry from the lcdwiki size drawing:
  PCB 27.78 (W) x 39.22 (H) mm; four O2.0 holes 2.5 mm from each edge
  header: 7 pins, pitch 2.54, in the same row as the top holes (2.5 mm below
          the top edge), first pin 6.27 mm from the left edge (GND ... BLK)
  LCD glass 25.8 x 29.22 mm, its top edge 5.0 mm below the PCB top edge
  active area 23.4 x 23.4 mm, 1.33 mm below the glass top, centred horizontally
Boxes only (KiCad ignores VRML Cylinder). Units 0.1 inch. Local frame: origin at
PCB centre, +Y = module top edge (header side), z = 0 is the board-facing PCB
face, -Z points away from the board (viewer side when looking at the bottom)."""
from pathlib import Path

OUT = Path(__file__).with_name("models") / "display_module.wrl"
U = 1 / 2.54
W, H = 27.78, 39.22
T_PCB, T_LCD = 1.2, 1.6


def mat(d, s=(0.2, 0.2, 0.2), sh=0.3):
    return (f"appearance Appearance {{ material Material {{ diffuseColor {d[0]} {d[1]} {d[2]} "
            f"specularColor {s[0]} {s[1]} {s[2]} shininess {sh} }} }}")


def box(cx, cy, cz, sx, sy, sz, m):
    return (f"Transform {{ translation {cx*U:.4f} {cy*U:.4f} {cz*U:.4f} children Shape {{ {m} "
            f"geometry Box {{ size {sx*U:.4f} {sy*U:.4f} {sz*U:.4f} }} }} }}\n")


pcb = mat((0.04, 0.12, 0.30), (0.2, 0.2, 0.3), 0.4)
glass = mat((0.03, 0.03, 0.04), (0.8, 0.8, 0.9), 0.9)
screen = mat((0.10, 0.35, 0.40), (0.9, 0.9, 1.0), 1.0)
frame = mat((0.72, 0.72, 0.75), (0.6, 0.6, 0.6), 0.5)
pin = mat((0.85, 0.72, 0.35), (0.9, 0.8, 0.5), 0.8)
black = mat((0.08, 0.08, 0.08))
hole = mat((0.85, 0.75, 0.45), (0.9, 0.85, 0.6), 0.8)   # gold-plated hole rings

s = "#VRML V2.0 utf8\n# 1.3in IPS ST7789 7-pin module (27.78 x 39.22 mm). Generated by gen_display_wrl.py\n"
# PCB: z 0 .. -1.2
s += box(0, 0, -T_PCB / 2, W, H, T_PCB, pcb)
# LCD glass 25.8 x 29.22, top edge 5.0 below PCB top -> centre y = H/2 - 5.0 - 29.22/2
gy = H / 2 - 5.0 - 29.22 / 2
s += box(0, gy, -T_PCB - 0.5, 25.8, 29.22, 1.0, frame)      # metal frame / backlight
s += box(0, gy, -T_PCB - 1.0 - 0.3, 25.8, 29.22, 0.6, glass)  # glass
# active area 23.4 sq, 1.33 below glass top
ay = H / 2 - 5.0 - 1.33 - 23.4 / 2
zface = -T_PCB - T_LCD
s += box(0, ay, zface - 0.03, 23.4, 23.4, 0.06, screen)
for (cx, cy, sx, sy) in ((0, ay + 10.7, 21.4, 0.5), (0, ay - 10.7, 21.4, 0.5), (10.7, ay, 0.5, 21.4), (-10.7, ay, 0.5, 21.4)):
    s += box(cx, cy, zface - 0.07, sx, sy, 0.04, black)
# corner holes (drawn as gold squares on both faces)
for hx in (-(W / 2 - 2.5), W / 2 - 2.5):
    for hy in (-(H / 2 - 2.5), H / 2 - 2.5):
        s += box(hx, hy, 0.01, 3.2, 3.2, 0.02, hole)
        s += box(hx, hy, -T_PCB - 0.01, 3.2, 3.2, 0.02, hole)
        s += box(hx, hy, -T_PCB / 2, 2.0, 2.0, T_PCB + 0.06, black)   # the hole itself
# 7-pin header row: y = H/2 - 2.5, x from -(W/2 - 6.27) in 2.54 steps; straight pins pointing to the board (+Z)
py = H / 2 - 2.5
x0 = -(W / 2 - 6.27)
s += box(x0 + 3 * 2.54, py, 1.27, 7 * 2.54, 2.54, 2.54, black)   # header plastic on the board-facing side
for i in range(7):
    s += box(x0 + i * 2.54, py, 2.6, 0.64, 0.64, 5.2, pin)
OUT.write_text(s, encoding="utf-8")
print("wrote", OUT, f"| glass centre y {gy:.2f}, active centre y {ay:.2f}, header y {py:.2f}, first pin x {x0:.2f}")
